create table categoria (id bigint generated by default as identity, nome varchar(255), primary key (id));
create table item_categoria (categoria_id bigint not null, item_id bigint not null, primary key (categoria_id, item_id));
create table itens (data timestamp(6), id bigint generated by default as identity, descricao varchar(255), endereco varchar(255), nome varchar(255), status varchar(255) check (status in ('MATCHING','EM_DEVOLUCAO','RECUPERADO')), tipo varchar(255) check (tipo in ('PERDIDO','ACHADO')), primary key (id));
create table usuarios (id bigint generated by default as identity, email varchar(255), nome varchar(255), senha varchar(255), primary key (id));
alter table if exists item_categoria add constraint FKjb1no42hxqipu6qnbugfj79sf foreign key (categoria_id) references categoria;
alter table if exists item_categoria add constraint FKbxxt9bpn91ipi3c5p1ps3f9ej foreign key (item_id) references itens;
